name: Build
on: push

env:
  STUNNEL_VERSION: 5.57

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: docker://alpine:3.13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and build stunnel
        run: ./build.sh

      - name: Upload binary to Releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_unmatched_files: true
          files: dist/*
